FROM maven:3.8.3-openjdk-17
LABEL authors="vitor_rt"

# configurações das variáveis de ambientes
ARG SPRING_DATASOURCE_DB_DEV_URL
ARG SPRING_DATASOURCE_DB_DEV_USERNAME
ARG SPRING_DATASOURCE_DB_DEV_PASSWORD
ARG SPRING_DATASOURCE_DB_DEV_DRIVER

ARG SPRING_MAIL_USERNAME
ARG SPRING_MAIL_PASSWORD

ENV SPRING_DATASOURCE_DB_DEV_URL=$SPRING_DATASOURCE_DB_DEV_URL
ENV SPRING_DATASOURCE_DB_DEV_USERNAME=$SPRING_DATASOURCE_DB_DEV_USERNAME
ENV SPRING_DATASOURCE_DB_DEV_PASSWORD=$SPRING_DATASOURCE_DB_DEV_PASSWORD
ENV SPRING_DATASOURCE_DB_DEV_DRIVER=$SPRING_DATASOURCE_DB_DEV_DRIVER

ENV SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME
ENV SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD

ENV PROJECT_HOME /usr/src/babycare-rest
ENV JAR_NAME babycare-0.0.1-SNAPSHOT.jar

# Criando destino do diretório
RUN mkdir -p ${PROJECT_HOME}
WORKDIR ${PROJECT_HOME}

# copiar daqui para lá
COPY . .

# gerar um .jar
RUN mvn clean package -DskipTests

# mover o jar para fora do /target
RUN mv ${PROJECT_HOME}/target/${JAR_NAME} ${PROJECT_HOME}/

ENTRYPOINT [ "java", "-jar", "babycare-0.0.1-SNAPSHOT.jar"]